// Common 5-letter words that can be used as target words
// prettier-ignore
export const targetWords = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
  'allow', 'alone', 'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple',
  'apply', 'arena', 'argue', 'arise', 'array', 'aside', 'asset', 'avoid', 'awake', 'award',
  'aware', 'badly', 'baker', 'bases', 'basic', 'beach', 'began', 'begin', 'being', 'below',
  'bench', 'billy', 'birth', 'black', 'blame', 'blind', 'block', 'blood', 'board', 'boost',
  'booth', 'bound', 'brain', 'brand', 'bread', 'break', 'breed', 'brief', 'bring', 'broad',
  'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'carry', 'catch', 'cause', 'chain',
  'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check', 'chest', 'chief', 'child',
  'china', 'chose', 'civil', 'claim', 'class', 'clean', 'clear', 'click', 'climb', 'clock',
  'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court', 'cover', 'craft', 'crash',
  'crazy', 'cream', 'crime', 'cross', 'crowd', 'crown', 'crude', 'curve', 'cycle', 'daily',
  'dance', 'dated', 'dealt', 'death', 'debut', 'delay', 'depth', 'doing', 'doubt', 'dozen',
  'draft', 'drama', 'drank', 'dream', 'dress', 'drill', 'drink', 'drive', 'drove', 'dying',
  'eager', 'early', 'earth', 'eight', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith', 'false', 'fault',
  'fiber', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flash', 'fleet',
  'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum', 'found', 'frame', 'frank',
  'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny', 'giant', 'given', 'glass', 'globe',
  'going', 'grace', 'grade', 'grand', 'grant', 'grass', 'grave', 'great', 'green', 'gross',
  'group', 'grown', 'guard', 'guess', 'guest', 'guide', 'happy', 'harry', 'heart', 'heavy',
  'hence', 'henry', 'horse', 'hotel', 'house', 'human', 'hurry', 'image', 'index', 'inner',
  'input', 'issue', 'japan', 'jimmy', 'joint', 'jones', 'judge', 'known', 'label', 'large',
  'laser', 'later', 'laugh', 'layer', 'learn', 'lease', 'least', 'leave', 'legal', 'level',
  'lewis', 'light', 'limit', 'links', 'lives', 'local', 'loose', 'lower', 'lucky', 'lunch',
  'lying', 'magic', 'major', 'maker', 'march', 'maria', 'match', 'maybe', 'mayor', 'meant',
  'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model', 'money', 'month', 'moral',
  'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie', 'music', 'needs', 'never', 'newly',
  'night', 'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often',
  'order', 'other', 'ought', 'paint', 'panel', 'paper', 'party', 'peace', 'peter', 'phase',
  'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant',
  'plate', 'point', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior',
  'prize', 'proof', 'proud', 'prove', 'queen', 'quick', 'quiet', 'quite', 'radio', 'raise',
  'range', 'rapid', 'ratio', 'reach', 'ready', 'realm', 'rebel', 'refer', 'relax', 'repay',
  'reply', 'right', 'rigid', 'rival', 'river', 'robin', 'roger', 'roman', 'rough', 'round',
  'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score', 'sense', 'serve', 'seven',
  'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt',
  'shock', 'shoot', 'short', 'shown', 'sides', 'sight', 'silly', 'since', 'sixth', 'sixty',
  'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile', 'smith', 'smoke', 'snake',
  'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak', 'speed', 'spend',
  'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand', 'start', 'state',
  'steam', 'steel', 'stick', 'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story',
  'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'table',
  'taken', 'taste', 'taxes', 'teach', 'teeth', 'terry', 'texas', 'thank', 'theft', 'their',
  'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those', 'three', 'threw',
  'throw', 'thumb', 'tiger', 'tight', 'timer', 'title', 'today', 'topic', 'total', 'touch',
  'tough', 'tower', 'track', 'trade', 'train', 'treat', 'trend', 'trial', 'tribe', 'trick',
  'tried', 'tries', 'truck', 'truly', 'trunk', 'trust', 'truth', 'twice', 'uncle', 'under',
  'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value',
  'video', 'virus', 'visit', 'vital', 'vocal', 'voice', 'waste', 'watch', 'water', 'weary',
  'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'women', 'world',
  'worry', 'worse', 'worst', 'worth', 'would', 'write', 'wrong', 'wrote', 'yield', 'young',
  'youth'
];

// Extended list of valid 5-letter words for guesses (includes target words + additional valid words)
// prettier-ignore
export const validWords = [
  ...targetWords,
  // Common 5-letter words
  'hello', 'world', 'games', 'words', 'plays', 'times', 'years', 'looks', 'makes', 'comes',
  'gives', 'takes', 'feels', 'means', 'works', 'keeps', 'seems', 'turns', 'shows', 'moves',
  'hands', 'books', 'lines', 'parts', 'helps', 'finds', 'calls', 'tells', 'wants', 'needs',
  'opens', 'takes', 'stops', 'talks', 'walks', 'reads', 'lives', 'loves', 'hates', 'likes',
  'knows', 'hopes', 'tries', 'falls', 'rises', 'rides', 'flies', 'jumps',
  // Additional valid words from dictionaries
  'aahed', 'aalii', 'aargh', 'abaca', 'abaci', 'abaft', 'abaka', 'abamp', 'abash', 'abate',
  'abaya', 'abbey', 'abbot', 'abear', 'abele', 'abers', 'abets', 'abhor', 'abide', 'abled',
  'abler', 'ables', 'abmho', 'abode', 'abohm', 'aboil', 'aboma', 'aboon', 'abort', 'abray',
  'abrim', 'abrin', 'abris', 'abuna', 'abune', 'abuts', 'abuzz', 'abyes', 'abysm', 'abyss',
  'acais', 'acari', 'accas', 'accoy', 'acedy', 'acers', 'aceta', 'achar', 'ached', 'aches',
  'achoo', 'acids', 'acidy', 'acing', 'acini', 'ackee', 'acker', 'acmes', 'acmic', 'acned',
  'acnes', 'acock', 'acold', 'acorn', 'acred', 'acres', 'acrid', 'acron', 'acted', 'actin',
  'acton', 'actos', 'acyls', 'adage', 'adapt', 'adaws', 'adays', 'addax', 'added', 'adder',
  'addio', 'addle', 'adeem', 'adept', 'adhan', 'adieu', 'adios', 'adits', 'adjag', 'admix',
  'adobe', 'adobo', 'adore', 'adorn', 'adown', 'adoze', 'adrad', 'adred', 'adsum', 'adunc',
  'adust', 'advew', 'aecia', 'aedes', 'aegis', 'aeons', 'aeros', 'aesir', 'afald', 'afars', 
  'afear', 'affix', 'afire', 'aflaj', 'afoot', 'afore', 'afoul', 'afrit', 'afros',
  'agama', 'agape', 'agars', 'agast', 'agate', 'agave', 'agaze', 'agene', 'agers', 'agger',
  'aggie', 'aggro', 'aghas', 'agile', 'aging', 'agios', 'agism', 'agist', 'agita', 'aglet',
  'agley', 'agloo', 'aglow', 'agmas', 'agmip', 'agone', 'agons', 'agony', 'agood', 'agora',
  'agria', 'agrin', 'agros', 'agued', 'agues', 'aguti', 'ahead', 'aheap', 'ahent', 'ahigh',
  'ahind', 'ahing', 'ahint', 'ahold', 'ahull', 'ahuru', 'aider', 'aides', 'aidoi', 'aidos',
  'aiery', 'aigas', 'aight', 'ailed', 'aimed', 'aimer', 'ainee', 'ainga', 'aioli', 'aired',
  'airer', 'airns', 'airth', 'airts', 'aisle', 'aitch', 'aitus', 'aiver', 'aizle', 'ajapa',
  'ajiva', 'ajuga', 'ajwan', 'akees', 'akela', 'akene', 'aking', 'akita', 'akkas', 'alaap',
  'alack', 'alamo', 'aland', 'alane', 'alang', 'alans', 'alant', 'alapa', 'alaps', 'alary',
  'alate', 'alays', 'albas', 'albee', 'albos', 'alcid', 'alcos', 'aldea', 'alder', 'aldol',
  'aleak', 'alear', 'aleck', 'alecs', 'alefs', 'aleft', 'aleme', 'aleye', 'alfas', 'algae',
  'algas', 'algid', 'algin', 'algor', 'algum', 'alias', 'alibi', 'alick', 'alifs', 'align',
  'alike', 'aline', 'alist', 'alive', 'aliya', 'alkie', 'alkos', 'alkyd', 'alkyl', 'allay',
  'allee', 'allel', 'alley', 'allis', 'allod', 'alloy', 'allyl', 'almah', 'almas', 'almeh',
  'almes', 'almud', 'almug', 'alods', 'aloed', 'aloes', 'aloft', 'aloha', 'aloin', 'alone',
  'along', 'aloof', 'aloud', 'alowe', 'alpha', 'altar', 'alter', 'altho', 'altos', 'alula',
  'alums', 'alure', 'alway', 'amahs', 'amain', 'amalg', 'amang', 'amans', 'amant', 'amate',
  'amaze', 'amban', 'amber', 'ambit', 'amble', 'ambos', 'ambry', 'ameba', 'ameer', 'amend',
  'amens', 'ament', 'amias', 'amice', 'amici', 'amide', 'amido', 'amids', 'amies', 'amiga',
  'amigo', 'amine', 'amino', 'amins', 'amirs', 'amiss', 'amity', 'amlas', 'ammil', 'ammon',
  'ammos', 'amnia', 'amnic', 'amnio', 'amoks', 'amole', 'among', 'amort', 'amour', 'amove',
  'amowt', 'amped', 'ample', 'amply', 'ampul', 'amrit', 'amuck', 'amuse',
  // Additional common 5-letter words
  'badge', 'bagel', 'balls', 'bands', 'banks', 'barks', 'beard', 'bears', 'beast', 'beats',
  'belly', 'bikes', 'bills', 'birds', 'blade', 'blank', 'blast', 'blaze', 'bleed', 'blend',
  'bless', 'blink', 'bloom', 'blown', 'blues', 'blunt', 'blush', 'boast', 'boats', 'bobby',
  'bones', 'bonus', 'boots', 'boxes', 'brake', 'brass', 'brave', 'brick', 'bride', 'brink',
  'brook', 'brush', 'buddy', 'bunch', 'bunny', 'burst', 'buses', 'buzzy', 'cakes', 'calls',
  'camel', 'camps', 'canal', 'candy', 'canoe', 'cards', 'cared', 'cargo', 'carve', 'cases',
  'caves', 'cease', 'chalk', 'champ', 'cheat', 'cheek', 'cheer', 'chess', 'chick', 'chill',
  'chips', 'choir', 'clamp', 'clerk', 'cliff', 'cloth', 'clubs', 'clues', 'coats', 'codes',
  'coins', 'coral', 'costs', 'couch', 'cough', 'crack', 'crisp', 'crops', 'cruel', 'crush',
  'dairy', 'daisy', 'deals', 'debug', 'decks', 'delta', 'dense', 'desks', 'diced', 'diets',
  'digit', 'dirty', 'disco', 'diver', 'dizzy', 'dodge', 'dolls', 'doors', 'doses', 'dough',
  'doves', 'drags', 'drake', 'draws', 'dried', 'drops', 'drugs', 'drums', 'drunk', 'ducks',
  'dunes', 'dusty', 'eagle', 'eaten', 'eater', 'edges', 'elder', 'elect', 'email', 'essay',
  'exams', 'excel', 'exits', 'fable', 'faced', 'facts', 'faded', 'fails', 'fairy', 'falls',
  'fancy', 'farms', 'fatal', 'favor', 'fears', 'feast', 'feeds', 'fence', 'fetch', 'fewer',
  'fiery', 'files', 'fills', 'films', 'fines', 'fired', 'fires', 'firms', 'flags', 'flame',
  'flare', 'flask', 'flesh', 'float', 'flock', 'flood', 'flour', 'flows', 'flute', 'folks',
  'fonts', 'foods', 'fools', 'forge', 'forms', 'freed', 'fried', 'frost', 'fuels', 'funds',
  'fuzzy', 'gangs', 'gates', 'gears', 'genre', 'ghost', 'gifts', 'girls', 'gives', 'gloom',
  'glory', 'glove', 'glows', 'goals', 'goats', 'goods', 'grain', 'grape', 'graph', 'grasp',
  'greed', 'greet', 'grief', 'grill', 'grind', 'grips', 'grove', 'grows', 'guilt', 'habit',
  'hails', 'hairs', 'halls', 'handy', 'hangs', 'harsh', 'haste', 'hated', 'hates', 'heads',
  'heals', 'heard', 'hedge', 'heels', 'helps', 'herbs', 'hides', 'highs', 'hills', 'hinds',
  'hints', 'hired', 'hires', 'hoard', 'hobby', 'holds', 'holes', 'homes', 'honey', 'hooks',
  'hoped', 'hopes', 'horns', 'hours', 'howls', 'humor', 'hurts', 'icons', 'ideal', 'ideas',
  'idiom', 'imply', 'inbox', 'indie', 'items', 'jails', 'james', 'jeans', 'jewel', 'joins',
  'jokes', 'juice', 'jumbo', 'keeps', 'kicks', 'kills', 'kinds', 'kings', 'kitty', 'knees',
  'knife', 'knock', 'knots', 'knows', 'labor', 'lacks', 'lakes', 'lands', 'lanes', 'lasts',
  'ledge', 'lemon', 'lever', 'liked', 'likes', 'lined', 'lines', 'lions', 'lists', 'lived',
  'liver', 'loans', 'lobby', 'locks', 'lodge', 'logic', 'loops', 'lords', 'loser', 'loses',
  'loved', 'lover', 'loves', 'loyal', 'lungs', 'mails', 'makes', 'males', 'malls', 'mange',
  'marks', 'marry', 'masks', 'meals', 'meats', 'medal', 'meets', 'melon', 'melts', 'menus',
  'mercy', 'merge', 'merit', 'merry', 'meter', 'miles', 'mills', 'minds', 'mines', 'mixes',
  'moats', 'modal', 'modes', 'monks', 'moods', 'moths', 'mowed', 'myths', 'nails', 'naked',
  'named', 'names', 'nasty', 'nerve', 'ninja', 'ninth', 'noble', 'nodes', 'nosed', 'noses',
  'notes', 'oasis', 'oaths', 'older', 'olive', 'omega', 'onion', 'opens', 'opera', 'opted',
  'orbit', 'organ', 'ounce', 'outer', 'owing', 'owned', 'owner', 'oxide', 'paced', 'pages',
  'pairs', 'panic', 'pants', 'parks', 'parts', 'pasta', 'paste', 'patch', 'paths', 'pause',
  'peaks', 'pears', 'penny', 'perch', 'perks', 'petty', 'picks', 'pills', 'pinch', 'pipes',
  'pizza', 'plays', 'plaza', 'plots', 'plugs', 'poems', 'poets', 'poles', 'polls', 'pools',
  'porch', 'poses', 'posts', 'probe', 'props', 'proxy', 'psalm', 'pulls', 'pumps', 'punch',
  'pupil', 'purse', 'pushy', 'quals', 'query', 'quest', 'queue', 'quote', 'races', 'racks',
  'raids', 'rails', 'rains', 'ranks', 'rated', 'rates', 'reads', 'recap', 'reign', 'relay',
  'remix', 'rides', 'ridge', 'rifle', 'rings', 'rises', 'risks', 'roads', 'roars', 'roast',
  'robes', 'robot', 'rocks', 'rocky', 'roles', 'rolls', 'roofs', 'rooms', 'roots', 'ropes',
  'roses', 'ruins', 'ruled', 'ruler', 'rules', 'rumor', 'rusty', 'sails', 'saint', 'salad',
  'sales', 'salon', 'sandy', 'sauce', 'saved', 'saves', 'scare', 'scent', 'screw', 'seals',
  'seats', 'seeds', 'seems', 'sells', 'sends', 'setup', 'sever', 'shade', 'shake', 'shame',
  'shark', 'shave', 'shiny', 'ships', 'shoes', 'shops', 'shore', 'shots', 'shows', 'shuts',
  'signs', 'sings', 'sinks', 'sites', 'sizes', 'skate', 'skins', 'skips', 'skull', 'slate',
  'slave', 'slips', 'slope', 'slots', 'smell', 'snaps', 'sneak', 'sniff', 'snore', 'snowy',
  'socks', 'soils', 'solar', 'songs', 'sorts', 'souls', 'soups', 'spark', 'spell', 'spike',
  'spine', 'spoon', 'spots', 'spray', 'squad', 'stack', 'stain', 'stair', 'stale', 'stamp',
  'stare', 'stars', 'stays', 'steal', 'steep', 'steer', 'stems', 'steps', 'stern', 'sting',
  'stink', 'stomp', 'stool', 'stops', 'surge', 'swaps', 'swear', 'sweat', 'sweep', 'swift',
  'swing', 'swiss', 'sword', 'tails', 'takes', 'tales', 'talks', 'tapes', 'tasks', 'teams',
  'tears', 'teddy', 'tells', 'tense', 'tenth', 'terms', 'tests', 'texts', 'thief', 'thump',
  'tidal', 'tiles', 'timed', 'timer', 'tired', 'toast', 'token', 'tombs', 'tonic', 'tools',
  'tooth', 'torch', 'tours', 'towns', 'toxic', 'trail', 'trait', 'tramp', 'trash', 'trees',
  'trips', 'tubes', 'tuned', 'turns', 'twins', 'twist', 'typed', 'types', 'unfed', 'urged',
  'users', 'using', 'utter', 'vapor', 'vault', 'veins', 'venue', 'verbs', 'verse', 'views',
  'viral', 'voids', 'votes', 'wages', 'wagon', 'waist', 'waits', 'wakes', 'walks', 'walls',
  'wants', 'warms', 'warns', 'waves', 'wears', 'weeds', 'weeks', 'weird', 'wells', 'welsh',
  'wheat', 'widow', 'width', 'winds', 'wines', 'wings', 'winks', 'wipes', 'wired', 'wires',
  'witch', 'wives', 'woods', 'worms', 'wound', 'wraps', 'yards', 'yeast', 'zones'
];

/**
 * Returns a random 5-letter target word from the predefined list.
 *
 * @returns {string} A randomly selected 5-letter word in lowercase.
 * @throws {Error} If a valid string cannot be retrieved from the target words list.
 */
export function getRandomTargetWord(): string {
  const randomIdx = Math.floor(Math.random() * targetWords.length);
  const randomWord = targetWords[randomIdx];
  if (typeof randomWord !== 'string') {
    throw new Error('[Words]: Failed to grab a random target word');
  }
  return randomWord.toLowerCase();
}

export function isValidWord(word: string): boolean {
  return validWords.includes(word.toLowerCase());
}
